version: "3.8"
services:
  py: &py
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - BYBIT_API_KEY
      - BYBIT_SECRET
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
