# %%
from crypto_exchanges.repository.bybit.bybit_rest_repository import BybitRestRepository
from crypto_exchanges.resolvers.bybit.ccxt_ import init_ccxt_bybit_demo


def test_bybit_rest_repository_fetch_balance_demo():
    ccxt_bybit = init_ccxt_bybit_demo()
    repo = BybitRestRepository(ccxt_bybit)
    balance = repo.fetch_balance()

    assert type(balance.balance_in_btc) is float


# %%
ccxt_bybit = init_ccxt_bybit_demo()
resp = ccxt_bybit.fetch_balance()
print(resp)
# %%
{
    "info": {
        "retCode": "0",
        "retMsg": "OK",
        "result": {
            "list": [
                {
                    "totalEquity": "156456.59602569",
                    "accountIMRate": "0.001",
                    "totalMarginBalance": "100014.53530969",
                    "totalInitialMargin": "109.074553",
                    "accountType": "UNIFIED",
                    "totalAvailableBalance": "99905.46075668",
                    "accountMMRate": "0",
                    "totalPerpUPL": "0.03310453",
                    "totalWalletBalance": "100014.50220515",
                    "accountLTV": "0",
                    "totalMaintenanceMargin": "6.24538734",
                    "coin": [
                        {
                            "availableToBorrow": "",
                            "bonus": "0",
                            "accruedInterest": "0",
                            "availableToWithdraw": "50000",
                            "totalOrderIM": "0",
                            "equity": "50000",
                            "totalPositionMM": "0",
                            "usdValue": "50007.95",
                            "unrealisedPnl": "0",
                            "collateralSwitch": True,
                            "spotHedgingQty": "0",
                            "borrowAmount": "0.000000000000000000",
                            "totalPositionIM": "0",
                            "walletBalance": "50000",
                            "cumRealisedPnl": "0",
                            "locked": "0",
                            "marginCollateral": True,
                            "coin": "USDC",
                        },
                        {
                            "availableToBorrow": "",
                            "bonus": "0",
                            "accruedInterest": "0",
                            "availableToWithdraw": "1",
                            "totalOrderIM": "0",
                            "equity": "1",
                            "totalPositionMM": "0",
                            "usdValue": "54169.889489",
                            "unrealisedPnl": "0",
                            "collateralSwitch": False,
                            "spotHedgingQty": "0",
                            "borrowAmount": "0.000000000000000000",
                            "totalPositionIM": "0",
                            "walletBalance": "1",
                            "cumRealisedPnl": "0",
                            "locked": "0",
                            "marginCollateral": True,
                            "coin": "BTC",
                        },
                        {
                            "availableToBorrow": "",
                            "bonus": "0",
                            "accruedInterest": "0",
                            "availableToWithdraw": "1",
                            "totalOrderIM": "0",
                            "equity": "1",
                            "totalPositionMM": "0",
                            "usdValue": "2272.171227",
                            "unrealisedPnl": "0",
                            "collateralSwitch": False,
                            "spotHedgingQty": "0",
                            "borrowAmount": "0.000000000000000000",
                            "totalPositionIM": "0",
                            "walletBalance": "1",
                            "cumRealisedPnl": "0",
                            "locked": "0",
                            "marginCollateral": True,
                            "coin": "ETH",
                        },
                        {
                            "availableToBorrow": "",
                            "bonus": "0",
                            "accruedInterest": "0",
                            "availableToWithdraw": "49999.70224595",
                            "totalOrderIM": "54.65453319",
                            "equity": "49999.73534595",
                            "totalPositionMM": "2.97483365",
                            "usdValue": "50006.58530969",
                            "unrealisedPnl": "0.0331",
                            "collateralSwitch": True,
                            "spotHedgingQty": "0",
                            "borrowAmount": "0.000000000000000000",
                            "totalPositionIM": "54.40507865",
                            "walletBalance": "49999.70224595",
                            "cumRealisedPnl": "-0.29775405",
                            "locked": "0",
                            "marginCollateral": True,
                            "coin": "USDT",
                        },
                    ],
                }
            ]
        },
        "retExtInfo": {},
        "time": "1725757049778",
    },
    "timestamp": 1725757049778,
    "datetime": "2024-09-08T00:57:29.778Z",
    "USDC": {"free": 50000.0, "used": 0.0, "total": 50000.0, "debt": 0.0},
    "BTC": {"free": 1.0, "used": 0.0, "total": 1.0, "debt": 0.0},
    "ETH": {"free": 1.0, "used": 0.0, "total": 1.0, "debt": 0.0},
    "USDT": {"free": 49999.70224595, "used": 0.0, "total": 49999.70224595, "debt": 0.0},
    "free": {"USDC": 50000.0, "BTC": 1.0, "ETH": 1.0, "USDT": 49999.70224595},
    "used": {"USDC": 0.0, "BTC": 0.0, "ETH": 0.0, "USDT": 0.0},
    "total": {"USDC": 50000.0, "BTC": 1.0, "ETH": 1.0, "USDT": 49999.70224595},
    "debt": {"USDC": 0.0, "BTC": 0.0, "ETH": 0.0, "USDT": 0.0},
}

# %%
{
    "info": {
        "retCode": "0",
        "retMsg": "OK",
        "result": {
            "list": [
                {
                    "totalEquity": "156438.07015985",
                    "accountIMRate": "0.001",
                    "totalMarginBalance": "100001.73983197",
                    "totalInitialMargin": "109.08196906",
                    "accountType": "UNIFIED",
                    "totalAvailableBalance": "99892.65786291",
                    "accountMMRate": "0",
                    "totalPerpUPL": "-0.25825293",
                    "totalWalletBalance": "100001.99808491",
                    "accountLTV": "0",
                    "totalMaintenanceMargin": "6.24581196",
                    "coin": [
                        {
                            "availableToBorrow": "",
                            "bonus": "0",
                            "accruedInterest": "0",
                            "availableToWithdraw": "50000",
                            "totalOrderIM": "0",
                            "equity": "50000",
                            "totalPositionMM": "0",
                            "usdValue": "50012.05",
                            "unrealisedPnl": "0",
                            "collateralSwitch": True,
                            "spotHedgingQty": "0",
                            "borrowAmount": "0.000000000000000000",
                            "totalPositionIM": "0",
                            "walletBalance": "50000",
                            "cumRealisedPnl": "0",
                            "locked": "0",
                            "marginCollateral": True,
                            "coin": "USDC",
                        },
                        {
                            "availableToBorrow": "",
                            "bonus": "0",
                            "accruedInterest": "0",
                            "availableToWithdraw": "1.00036908",
                            "totalOrderIM": "0",
                            "equity": "1.00036908",
                            "totalPositionMM": "0",
                            "usdValue": "54166.62263087",
                            "unrealisedPnl": "0",
                            "collateralSwitch": False,
                            "spotHedgingQty": "0",
                            "borrowAmount": "0.000000000000000000",
                            "totalPositionIM": "0",
                            "walletBalance": "1.00036908",
                            "cumRealisedPnl": "-0.00000036",
                            "locked": "0",
                            "marginCollateral": True,
                            "coin": "BTC",
                        },
                        {
                            "availableToBorrow": "",
                            "bonus": "0",
                            "accruedInterest": "0",
                            "availableToWithdraw": "1",
                            "totalOrderIM": "0",
                            "equity": "1",
                            "totalPositionMM": "0",
                            "usdValue": "2269.707697",
                            "unrealisedPnl": "0",
                            "collateralSwitch": False,
                            "spotHedgingQty": "0",
                            "borrowAmount": "0.000000000000000000",
                            "totalPositionIM": "0",
                            "walletBalance": "1",
                            "cumRealisedPnl": "0",
                            "locked": "0",
                            "marginCollateral": True,
                            "coin": "ETH",
                        },
                        {
                            "availableToBorrow": "",
                            "bonus": "0",
                            "accruedInterest": "0",
                            "availableToWithdraw": "49979.44404595",
                            "totalOrderIM": "54.65453319",
                            "equity": "49979.44404595",
                            "totalPositionMM": "2.97483365",
                            "usdValue": "49989.68983197",
                            "unrealisedPnl": "-0.2582",
                            "collateralSwitch": True,
                            "spotHedgingQty": "0",
                            "borrowAmount": "0.000000000000000000",
                            "totalPositionIM": "54.40507865",
                            "walletBalance": "49979.70224595",
                            "cumRealisedPnl": "-0.29775405",
                            "locked": "0",
                            "marginCollateral": True,
                            "coin": "USDT",
                        },
                    ],
                }
            ]
        },
        "retExtInfo": {},
        "time": "1725757200229",
    },
    "timestamp": 1725757200229,
    "datetime": "2024-09-08T01:00:00.229Z",
    "USDC": {"free": 50000.0, "used": 0.0, "total": 50000.0, "debt": 0.0},
    "BTC": {"free": 1.00036908, "used": 0.0, "total": 1.00036908, "debt": 0.0},
    "ETH": {"free": 1.0, "used": 0.0, "total": 1.0, "debt": 0.0},
    "USDT": {
        "free": 49979.44404595,
        "used": 0.2582,
        "total": 49979.70224595,
        "debt": 0.0,
    },
    "free": {"USDC": 50000.0, "BTC": 1.00036908, "ETH": 1.0, "USDT": 49979.44404595},
    "used": {"USDC": 0.0, "BTC": 0.0, "ETH": 0.0, "USDT": 0.2582},
    "total": {"USDC": 50000.0, "BTC": 1.00036908, "ETH": 1.0, "USDT": 49979.70224595},
    "debt": {"USDC": 0.0, "BTC": 0.0, "ETH": 0.0, "USDT": 0.0},
}
